version: '3.1'
services:
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'urna'
      MYSQL_DATABASE: 'eleicoes'
      MYSQL_PASSWORD: 'eleicoes2022'
      MYSQL_ROOT_HOST: '%'
